#!/bin/bash
set -eou pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

function error {
	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}: line ${BASH_LINENO[0]}: ${*}"
	>&2 echo -e "${RED}${msg}${NC}"
	exit 2
}

vars_file_shell="$1/vars.sh"
vars_file_yaml="$1/vars.yml"

shift;

debug=()

# shellcheck disable=SC2214
while getopts ':fp-:' OPT; do
	if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
		OPT="${OPTARG%%=*}"       # extract long option name
		OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
		OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
	fi
	case "$OPT" in
		f|fast ) fast="true";;
		p|prepare ) prepare="true";;
		debug ) debug=( "-vvvvv" );;
		??* ) break;;  # long option
		\? )  break;;  # short option
	esac
done
shift $((OPTIND-1))

#shellcheck disable=SC1090
. "$vars_file_shell"

vault=()

#shellcheck disable=SC2154
var_vault_file="$vault_file"

if [ -f "$var_vault_file" ]; then
    vault=( '--vault-id' "$var_vault_file" )
elif [ "${FORCE_VAULT:-}" = 'true' ]; then
    vault=( '--vault-id' 'cloud@prompt')
fi

#shellcheck disable=SC2154
var_repo_dir="$repo_dir"
cd "$var_repo_dir"

if [ "${fast:-}" = 'true' ]; then
	echo "[cloud] skipping prepare project context (fast)..."
else
    prepare_args=()

    if [ "${prepare:-}" = 'true' ]; then
        prepare_args=( "${@}" )
    fi

	# Prepare the cloud context
	ANSIBLE_CONFIG=ansible.cfg ansible-playbook \
		${prepare_args[@]+"${prepare_args[@]}"} \
		${vault[@]+"${vault[@]}"} \
		${debug[@]+"${debug[@]}"} \
		-i hosts \
		-e env_vars_file="$vars_file_yaml" \
        prepare.ctx.yml || error "[error] prepare ctx"
fi

if [ "${prepare:-}" = 'true' ]; then
	echo "[cloud] skipping execute project context (prepare)..."
else
    #shellcheck disable=SC2154
    var_ctx_dir="$ctx_dir"

    # Execute the cloud context
    ANSIBLE_CONFIG=ansible.cfg ansible-playbook \
        ${vault[@]+"${vault[@]}"} \
        ${debug[@]+"${debug[@]}"} \
        -i "$var_ctx_dir/hosts" \
        -e env_vars_file="$vars_file_yaml" \
        main.yml "${@}" || error "[error] run ctx"
fi