- name: "{{ prepare_repos_extra_repo_link_title }} - create dest directory"
  file:
    path: "{{ prepare_repos_extra_repo_link_dest | dirname }}"
    state: directory
    mode: "{{ env_lax | bool | ternary('777', '755') }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_extra_repo_link_title }} - create link"
  file:
    src: "{{ prepare_repos_extra_repo_link_src | relpath(prepare_repos_extra_repo_link_dest | dirname) }}"
    dest: "{{ prepare_repos_extra_repo_link_dest }}"
    state: link
  no_log: "{{ env_no_log }}"
