- name: "{{ prepare_repos_layer_title }} - validate repository name"
  fail:
    msg: "repository name not defined"
  when: (prepare_repos_layer.repo | default('')) == ''
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_layer_title }} - validate repository"
  fail:
    msg: "repository {{ prepare_repos_layer.repo }} not found"
  when: prepare_repos_repos_dict[prepare_repos_layer.repo] is not defined
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_layer_title }} - main (outer)"
  include_tasks: "tasks/util/repo.yml"
  vars:
    repo_title: "{{ prepare_repos_layer_title }} - main"
    repo_main: "{{ prepare_repos_repos_dict[prepare_repos_layer.repo] }}"
    repo_ssh_src_dir: "{{ env_dir }}"
    repo_secrets_dir: "{{ prepare_repos_secrets_repos_dir }}/{{ prepare_repos_layer.repo }}"
    repo_default_dir: "{{ prepare_repos_layer_dest }}"
    repo_dev_base_dir: "{{ prepare_repos_dev_repos_dir }}"
    repo_dev_path: "{{ prepare_repos_env_path_map[prepare_repos_layer.repo] | default('') }}"
    repo_dev: "{{ env_dev }}"
    repo_lax: "{{ env_lax }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_layer_title }} - prepare_repos_layer_dir"
  set_fact:
    prepare_repos_layer_dir: "{{ repo_dir }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_layer_title }} - env repos"
  include_tasks: "tasks/util/repo.yml"
  vars:
    repo_title: "{{ prepare_repos_layer_title }} - env repo ({{ prepare_repos_layer_item.repo }})"
    repo_main: "{{ prepare_repos_repos_dict[prepare_repos_layer_item.repo] }}"
    repo_ssh_src_dir: "{{ env_dir }}"
    repo_secrets_dir: "{{ prepare_repos_secrets_repos_dir }}/{{ prepare_repos_layer_item.repo }}"
    repo_default_dir: "{{ prepare_repos_layer_dir }}/{{ prepare_repos_layer_item.dir }}"
    repo_dev_base_dir: "{{ prepare_repos_dev_repos_dir }}"
    repo_dev_path: "{{ prepare_repos_env_path_map[prepare_repos_layer_item.repo] | default('') }}"
    repo_dev: "{{ env_dev }}"
    repo_lax: "{{ env_lax }}"
  loop: "{{ prepare_repos_layer.ext_repos | default([]) }}"
  loop_control:
    loop_var: prepare_repos_layer_item
    label: "{{ prepare_repos_layer_item.repo }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]
