# Extra Repos

- name: "{{ prepare_repos_title }} - extra repos (local) - repos"
  include_tasks: "tasks/prepare_repos/layer.yml"
  vars:
    prepare_repos_layer: "{{ prepare_repos_item }}"
    prepare_repos_layer_title: >-
      {{ prepare_repos_title }} - extra repos (local) - repo
      [{{ prepare_repos_item.dir }} ({{ prepare_repos_item.repo }})]
    prepare_repos_layer_dest: >-
      {{ prepare_repos_extra_repos_dir + '/' + prepare_repos_item.dir }}
  loop: "{{ prepare_repos_ctx_extra_repos }}"
  loop_control:
    loop_var: prepare_repos_item
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_title }} - extra repos (local) - options"
  include_tasks: "tasks/prepare_repos/extra_repo.yml"
  vars:
    prepare_repos_extra_repo: "{{ prepare_repos_item }}"
    prepare_repos_extra_repo_name: "{{ prepare_repos_item.repo }}"
    prepare_repos_extra_repo_title: >-
      {{ prepare_repos_title }} - extra repo (local) - options
      [{{ prepare_repos_item.dir }} ({{ prepare_repos_extra_repo_name }})]
    prepare_repos_extra_repo_dir: >-
      {{ prepare_repos_extra_repos_dir + '/' + prepare_repos_item.dir }}
    prepare_repos_extra_repo_tmp_dir: >-
      {{ prepare_repos_extra_repos_tmp_dir + '/' + prepare_repos_item.dir }}
  loop: "{{ prepare_repos_ctx_extra_repos }}"
  loop_control:
    loop_var: prepare_repos_item
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Pods Repos (Local)

- name: "{{ prepare_repos_title }} - (var) prepare_repos_parent_pods_list - init"
  set_fact:
    prepare_repos_parent_pods_list: []
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_title }} - (var) prepare_repos_parent_pods_list - fill"
  set_fact:
    prepare_repos_parent_pods_list: >-
      {{
        prepare_repos_parent_pods_list
        + [{
          'type': 'node',
          'name': tmp_node_name,
          'pods': tmp_node.pods | default([])
        }]
      }}
  vars:
    tmp_node_name: "{{ tmp_item.name | default(tmp_item) }}"
    tmp_node_key: "{{ tmp_item.key | default(tmp_item.name | default(tmp_item)) }}"
    tmp_node: "{{ prepare_repos_nodes_dict[tmp_node_key] | default({}) }}"
  when: prepare_repos_nodes_dict[tmp_node_key] is defined
  loop: "{{ prepare_repos_nodes }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item.name | default(tmp_item) }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ prepare_repos_title }} - local pod repos"
  include_tasks: "tasks/prepare_repos/layer.yml"
  vars:
    prepare_repos_layer_name: "{{ prepare_repos_item.1.name | default(prepare_repos_item.1) }}"
    prepare_repos_layer_key: >-
      {{ prepare_repos_item.1.key | default(prepare_repos_item.1.name | default(prepare_repos_item.1)) }}
    prepare_repos_layer_label: >-
      {{
        prepare_repos_item.0.type + ' [' + prepare_repos_item.0.name + ']'
        + ' - pod [' + prepare_repos_layer_name + ']'
      }}
    prepare_repos_layer: "{{ prepare_repos_pods_dict[prepare_repos_layer_key] | default({}) }}"
    prepare_repos_layer_title: "{{ prepare_repos_title }} - local pod repo - {{ prepare_repos_layer_label }}"
    prepare_repos_layer_dest: >-
      {{
        env_ctx_dir
        + '/' + prepare_repos_item.0.type + '-pods/' + prepare_repos_item.0.name
        + '/pods/' + prepare_repos_layer_name
      }}
  when: prepare_repos_pods_dict[prepare_repos_layer_key] is defined
  loop: "{{ prepare_repos_parent_pods_list | subelements('pods') }}"
  loop_control:
    loop_var: prepare_repos_item
    label: "{{ prepare_repos_layer_label }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]
