- name: "{{ cloud_service_run_title }} - recursive - before"
  block:
    - name: "{{ cloud_service_run_title }} - cloud_service_run - before"
      set_fact:
        cloud_service_run: "{{ tmp_service }}"
        cloud_service_run_inner_title: >-
          {{ cloud_service_run_title }} - service [{{ tmp_service.description }}]
        cloud_service_run_delay_errors: >-
          {{
            cloud_service_delay_errors
            | default(tmp_service.delay_errors | default(false))
          }}
      vars:
        tmp_service: >-
          {{ cloud_service_run_list[cloud_service_run_idx | int] | default({}) }}
      no_log: "{{ env_no_log }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_run_inner_title }} - cloud_service_name_list"
      fail:
        msg: >-
          the service that would run ({{ cloud_service_run.name }}) has the same namespace
          ({{ cloud_service_run.namespace | default('') }}) that a parent or ancestor of
          this service ({{ tmp_item.name }}) has
      when: >-
        ((cloud_service_run.namespace | default('')) != '')
        and
        ((cloud_service_run.namespace | default('')) == (tmp_item.namespace | default('')))
      loop: "{{ cloud_service_next.next_list }}"
      loop_control:
        loop_var: tmp_item
        label: "{{ tmp_item.name }}"
      no_log: "{{ env_no_log }}"
      tags: ["no_print"]

  when: cloud_service_continue | bool
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- name: "{{ cloud_service_run_inner_title }} - result - initial"
  set_fact:
    cloud_service_result: {}
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- block:
    - name: "{{ cloud_service_run_inner_title }} - execute the service"
      include_tasks: "{{ inner_service_base_dir_prefix }}{{ inner_service_task }}"
      vars:
        cloud_service_top: false
        inner_service_state: >-
          {{
            cloud_service_run.absent | default(false) | bool
            | ternary('absent', cloud_service_state)
          }}
        inner_service_title: "{{ cloud_service_run_inner_title }} - inside"
        inner_service_name: "{{ cloud_service_run.name }}"
        inner_service_task: "{{ cloud_service_run.task }}"
        inner_service_namespace: "{{ cloud_service_run.namespace | default('') }}"
        inner_service_params: "{{ cloud_service_run.params | default({}) }}"
        inner_service_credentials: "{{ cloud_service_run.credentials | default({}) }}"
        inner_service_contents: "{{ cloud_service_run.contents | default({}) }}"
        inner_service_base_dir_prefix: "{{ cloud_service_run.base_dir_prefix }}"
        inner_service_tmp_dir: "{{ cloud_service_tmp_dir }}/{{ cloud_service_run.name }}"
        # Define an empty list for the case in which a service call another
        cloud_service_prepared_list: []
      when: cloud_service_continue | bool
      no_log: "{{ env_no_log }}"
      tags: ["no_print_skipped"]
  rescue:
    - name: "{{ cloud_service_run_inner_title }} - handle error (fail)"
      fail:
        msg: "error in service execution (see above logs for more details)"
      ignore_errors: "{{ cloud_service_run.ignore_errors | default(false) | bool }}"
      when: not (cloud_service_run_delay_errors | bool)
      no_log: "{{ env_no_log }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_run_inner_title }} - handle error (postpone)"
      set_fact:
        instance_errors: "{{ instance_errors + ['[error] ' + cloud_service_run_inner_title] }}"
      when: >-
        (cloud_service_run_delay_errors | bool)
        and
        (not (cloud_service_run.ignore_errors | default(false) | bool))
      no_log: "{{ env_no_log }}"
      tags: ["no_print"]

- name: "{{ cloud_service_run_title }} - cloud_service_run - after"
  set_fact:
    cloud_service_run: "{{ tmp_service }}"
    cloud_service_run_inner_title: "{{ cloud_service_run_title }} - service [{{ tmp_service.name }}]"
  vars:
    tmp_service: >-
      {{ cloud_service_run_list[cloud_service_run_idx | int] | default({}) }}
  when: cloud_service_continue | bool
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ cloud_service_run_inner_title }} - result - map"
  set_fact:
    cloud_service_result_map: >-
      {{
        cloud_service_result_map
        | combine({ cloud_service_run.name: cloud_service_result })
      }}
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ cloud_service_run_inner_title }} - cloud_service_run_idx"
  set_fact:
    cloud_service_run_idx: "{{ (cloud_service_run_idx | int) + 1 }}"
  when: cloud_service_continue | bool
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ cloud_service_run_inner_title }} - cloud_service_continue ({{ tmp_continue }})"
  set_fact:
    cloud_service_continue: "{{ tmp_continue }}"
  vars:
    tmp_continue_before: "{{ cloud_service_continue }}"
    tmp_continue: "{{ (cloud_service_run_idx | int) < (cloud_service_run_list | length) }}"
  when: tmp_continue_before | bool
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ cloud_service_run_inner_title }} - execute the next service"
  include_tasks: "tasks/services/cloud_service_run.yml"
  when: cloud_service_continue | bool
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
