- name: "{{ cloud_node_title }} - nodes (outer)"
  include_tasks: "cloud_node_item.yml"
  vars:
    cloud_node_name: "{{ cloud_node_item.name }}"
    cloud_node_item_title: >-
      {{ cloud_node_title }} - node [{{ cloud_node_item.description }}]
    cloud_node_item_state: >-
      {{
        cloud_node_item.absent | default(false) |
        ternary('absent', cloud_node_state)
      }}
    cloud_node_item_delay_errors: >-
      {{
        cloud_node_delay_errors
        | default(cloud_node_item.delay_errors | default(false))
      }}
  loop: "{{ cloud_node_list }}"
  loop_control:
    loop_var: cloud_node_item
    label: "{{ cloud_node_name }}"
  when: env_node in ['', cloud_node_name]
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
