- name: "{{ instance_info_title }} - instance_info_backup_dir"
  set_fact:
    instance_info_backup_dir: "{{ tmp_backup_dir }}"
    instance_info_backup_file: "{{ tmp_backup_dir }}/{{ tmp_backup_file }}"
    instance_info_backup_file_tmp: "{{ tmp_backup_dir }}/{{ tmp_backup_file }}.tmp"
  vars:
    tmp_backup_dir: "{{ instance_info_node.tmp_dir }}/backup"
    tmp_backup_file: "commit"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ instance_info_title }} - create the backup directory"
  become: "{{ instance_info_node.root | default(false) | bool }}"
  file:
    path: "{{ instance_info_backup_dir }}"
    state: directory
    mode: "{{ (env_lax | bool) | ternary('777', '755') }}"
  when: instance_info_type == 'before'
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- name: >-
    {{ instance_info_title }} -
    create the temporary file to verify if there was a change in the commit
  become: "{{ instance_info_node.root | default(false) | bool }}"
  copy:
    content: "{{ env_commit }}"
    dest: "{{ instance_info_backup_file_tmp }}"
    mode: "{{ (env_lax | bool) | ternary('666', '640') }}"
  when: instance_info_type == 'before'
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- block:
    - name: >-
        {{ instance_info_title }} - create the file to verify if there was a change
        in the commit, if it was not created before
      become: "{{ instance_info_node.root | default(false) | bool }}"
      copy:
        force: no
        content: ""
        dest: "{{ instance_info_backup_file }}"
        mode: "{{ (env_lax | bool) | ternary('666', '640') }}"
      no_log: "{{ env_no_log }}"
      tags: ["no_print_skipped"]

    - name: "{{ instance_info_title }} - get the difference of the 2 commit files (old and current)"
      become: "{{ instance_info_node.root | default(false) | bool }}"
      command: "diff {{ instance_info_backup_file_tmp }} {{ instance_info_backup_file }}"
      register: instance_info_diff
      failed_when: instance_info_diff.rc > 1
      changed_when: instance_info_diff.rc == 1
      no_log: "{{ env_no_log }}"
      tags: ["no_print_skipped"]

    - name: "{{ instance_info_title }} - instance_info_skip (define)"
      set_fact:
        instance_info_skip: "{{ not instance_info_diff.changed }}"
      no_log: "{{ env_no_log }}"
      tags: ["no_print"]

  when: (instance_info_type == 'before') and (not (env_force | bool))
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- name: >-
    {{ instance_info_title }} -
    update the file to verify if there was a change in the commit
    (for newer runs)
  become: "{{ instance_info_node.root | default(false) | bool }}"
  copy:
    remote_src: yes
    src: "{{ instance_info_backup_file_tmp }}"
    dest: "{{ instance_info_backup_file }}"
    mode: "{{ (env_lax | bool) | ternary('666', '640') }}"
  when: instance_info_type == 'after'
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
