- name: "{{ node_setup_title }} - validate instance type - node name"
  fail:
    msg: "instance_type ({{ instance_type }}) should be {{ tmp_name }}"
  vars:
    tmp_name: "{{ node_setup_node.name }}"
  when: (tmp_name != instance_type) and (ansible_connection != 'local')
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ node_setup_title }} - host users"
  include_tasks: "tasks/nodes/node_setup_item.yml"
  vars:
    node_setup_item_key: "{{ node_setup_item.name }}"
    node_setup_item_title: "{{ node_setup_title }} - host user [{{ node_setup_item_key }}]"
    node_setup_item_credentials: "{{ node_setup_node.credentials[node_setup_item_key] }}"
    ansible_user: "{{ node_setup_item_credentials.host_user }}"
    ansible_become_pass: "{{ node_setup_item_credentials.host_pass | default('') }}"
    ansible_ssh_private_key_file: "{{ node_setup_item.ssh_key_path | default('') }}"
  when: not (node_setup_item.skip_setup | default(false) | bool)
  loop: "{{ node_setup_node.host_users | default([]) }}"
  loop_control:
    loop_var: node_setup_item
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
