### SSH File(s) ###

- name: "{{ pre_prepare_node_title }} - create the ssh key file dir(s)"
  file:
    path: "{{ tmp_item }}"
    state: directory
    mode: 0755
  when: tmp_item != ''
  loop: >-
    {{
      pre_prepare_node_item.host_users | default([])
      | selectattr('ssh_key_dir', 'defined')
      | map(attribute='ssh_key_dir')
      | list
      | unique
    }}
  loop_control:
    loop_var: tmp_item
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- name: "{{ pre_prepare_node_title }} - generate the ssh key file(s)"
  copy:
    src: "{{ tmp_src }}"
    dest: "{{ tmp_path }}"
    mode: 0600
  vars:
    tmp_src: "{{ tmp_item.ssh_key_src | default('') }}"
    tmp_path: "{{ tmp_item.ssh_key_path | default('') }}"
  when: tmp_path != ''
  loop: "{{ pre_prepare_node_item.host_users | default([]) }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_path }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
