- name: "{{ node_prepare_title }} - create the node directories"
  become: "{{ node_prepare_node.root | default(false) }}"
  file:
    path: "{{ node_prepare_item }}"
    state: directory
    mode: "{{ env_lax | bool | ternary('777', '755') }}"
  loop:
    - "{{ node_prepare_node.node_dir }}"
    - "{{ node_prepare_node.tmp_dir }}"
  loop_control:
    loop_var: node_prepare_item
  no_log: "{{ env_no_log }}"

- name: "{{ node_prepare_title }} - node_prepare_transfer_list (init)"
  set_fact:
    node_prepare_transfer_list: []
    node_prepare_transfer_input: >-
      {{
        node_prepare_node.general_data
        | combine({ 'dependencies': tmp_dependencies })
      }}
  vars:
    tmp_dependencies: >-
      {{
        ctx_node_dependencies[node_prepare_node.name]
        | default(node_prepare_node.general_data.dependencies | default({}))
      }}
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ node_prepare_title }} - node_prepare_transfer_list (fill)"
  set_fact:
    node_prepare_transfer_list: >-
      {{ node_prepare_transfer_list + [tmp_transfer_item] }}
  vars:
    tmp_no_empty_lines: "{{ env.meta.template_no_empty_lines | default(false) }}"
    tmp_base_dir: >-
      {{
        tmp_item.is_base_dir | default(false) | bool
        | ternary(node_prepare_node.base_dir, node_prepare_node.node_dir)
      }}
    tmp_transfer_item:
      content: "{{ tmp_item.src }}"
      dest: "{{ tmp_base_dir }}/{{ tmp_item.dest }}"
      tmp_dest: "{{ node_prepare_node.tmp_dir }}/{{ tmp_item.dest }}"
      mode: "{{ tmp_item.mode }}"
      dir_mode: "{{ tmp_item.dir_mode }}"
      no_empty_lines: "{{ tmp_item.no_empty_lines | default(tmp_no_empty_lines) }}"
  when: tmp_item.when | default(true, true) | bool
  loop: "{{ node_prepare_node.prepared_transfer | default([]) }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item.dest }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ node_prepare_title }} - transfer (outer)"
  include_tasks: "tasks/util/transfer.yml"
  vars:
    transfer_title: "{{ node_prepare_title }} - transfer"
    transfer_become: "{{ node_prepare_node.root | default(false) }}"
    transfer_list: "{{ node_prepare_transfer_list }}"
    transfer_prepared: true
    transfer_input: "{{ node_prepare_transfer_input }}"
  when: (node_prepare_transfer_list | length) > 0
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
