#!/bin/bash
export repo_dir=''
export ctx_dev_dir=''
export vault_file=''
export secrets_cloud_dir=''
export dev_repos_dir=''
export ctx=''
export path_map_file=''
export repo_run_file=''
export project=''
export ctx_dir=''
export env_params_file=''
export env_dev=''
export env_dir=''
export env_file=''
export env_lax=''
export secrets_ctx_dir=''